kind: Service
apiVersion: v1
metadata:
  name: apiservice
spec:
  selector:
    app: apiservice
  ports:
  - protocol: "TCP"
    port: 8084
    targetPort: 8084
    nodePort: 30004
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiservice-deployment
  labels:
    app: apiservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apiservice
  template:
    metadata:
      labels:
        app: apiservice
    spec:
      containers:
      - name: apiservice
        image: skiprope/apiservice:latest
        ports:
        - containerPort: 8084
          name: server
          protocol: TCP
        env:
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379  
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: SKIPROPECONFIGS_HEALTH_ETCDURL
            value: http://etcd:2379/health
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://apiservice:8082
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: skiprope
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        