kumuluzee:
  name: apiservice
  version: 1.0.0
  env:
    name: dev
  server:
    http:
      port: 8084
    base-url: http://localhost:8084

  health:
    checks:
      disk-space-health-check:
        threshold: 100000000

  metrics:
    web-instrumentation:
      - name: metrics-endpoint
        url-pattern: /api/*
        status-codes: "200, 500"
    servlet:
      enabled: true

  discovery:
      etcd:
        hosts: http://localhost:2379

  config:
    etcd:
      hosts: http://localhost:2379

# Settings and configurations
skiprope-configs:
  health:
    etcd-url: http://localhost:2379/health